name: "Semantic PR"
description: "Helps ensure that pull requests will be merged and creates the desired outcome of semantic-release. "
author: "levibostian"
inputs: 
 token:
    description: "A GitHub token used for making requests to Github's API"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'check'  
  color: 'green'