name: "Semantic PR"
description: "Helps ensure that pull requests will be merged and creates the desired outcome of semantic-release. "
author: "levibostian"
inputs: 
  readToken:
    description: "GitHub personal access token that has read-only access to the repository."
    required: true
  writeToken:
    description: "GitHub personal access token that has read and write access to the repository."
    required: true
  branchTypeWarning:
    description: 'Sets rules on the types of commits allowed on a specific branch. Example: {"beta": "fix,docs"} gives a warning on the pull request if a pull request is made into the beta branch with a type thats not fix or docs.'
    required: false
    default: "{}"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'check'  
  color: 'green'