name: Deploy action

on:
  push:
    branches: [main, beta, alpha]
  workflow_dispatch: # allow manually deploying from Actions tab

jobs:
  deploy-git-tag-and-release:
    name: Deploy git tags
    runs-on: ubuntu-latest
    permissions:
      contents: write # push git commits/releases 
      issues: write # comments on issues 
      pull-requests: write # comment on PRs 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run compile 

      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          # Hard-coding version as workaround https://github.com/semantic-release/commit-analyzer/issues/517#issuecomment-1697193361
          semantic_version: 18
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0 
            @semantic-release/commit-analyzer@9
            @semantic-release/release-notes-generator@10
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@8
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  major-version-bump:
    runs-on: ubuntu-latest
    needs: deploy-git-tag-and-release # to wait for new git tag to be made. 
    permissions:
      contents: write # so it can push a tag
    steps:
      # Will automatically release vX for major releases after each deployment
      - uses: Actions-R-Us/actions-tagger@v2