name: Deploy action

on:
  push:
    branches: [main, beta, alpha]

permissions: read-all

jobs:
  deploy:
    name: Deploy git tags
    runs-on: ubuntu-latest
    permissions:
      contents: write # push git commits/releases 
      issues: write # comments on issues 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run compile 

      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            @semantic-release/commit-analyzer@9
            @semantic-release/release-notes-generator@10
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@8