name: Action major version bump 

on:
  release:
    types: [published, edited]

permissions: read-all

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write # so it can push a tag
    steps:
      # Will automatically release vX for major releases after each deployment
      - uses: Actions-R-Us/actions-tagger@v2