# Reusable GitHub Actions Workflow that allows other repos on GitHub to use this workflow. 
# Integrate faster!
name: Lint pull request title to assert it uses conventional commits 

on:
  workflow_call: 

jobs:
  lint-pull-request-title-conventional-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Lint pull request title to assert it uses conventional commits
      uses: levibostian/action-semantic-pr@v3