name: Test Action 

on:
  push: # test on push the action ignores request. 
  pull_request: # test that we can edit the PR title to re-run the action
    types: [opened, reopened, edited, synchronize]

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies
        run: npm ci
      - name: Compile action before testing it 
        run: npm run compile
      - name: Install @commitlint/config-angular to test custom rules work
        run: npm i @commitlint/config-angular
      # Thanks: https://github.com/actions/typescript-action/blob/b4f07da86601110b682c6f45ff575f5fbd0f8cdf/.github/workflows/test.yml#L18      
      - name: Test Action
        uses: ./ 
        with:
          token: ${{ secrets.COMMENT_BOT_TOKEN }}
          rules: "@commitlint/config-angular"