name: Test Action 

on:
  pull_request: # test that we can edit the PR title to re-run the action
    types: [opened, reopened, edited, synchronize, labeled]

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to comment 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - name: Compile action before testing it 
        run: npm run compile

      # I have been getting false positives when running action in project when node_modules/
      # exists. We can `npm ci` above but when action runs in other projects, that dir will not exist. 
      - name: Make environment more realistic to running action on project 
        run: rm -rf node_modules/

      - name: Test Action
        uses: ./
